name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ./target
            ~/.cargo
          key: ${{ runner.os }}-${{ hashFiles('Cargo.toml') }}

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true


      - name: Install dependencies
        run: sudo apt update && sudo apt install -y libdbus-1-dev libdbus-1-dev pkg-config

      - name: Build
        run: cargo build --verbose

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - name: Run tests
        run: cargo test --features full --verbose
